version: '3'

services:
  app:
    container_name: webapp-rgw
    image: baltig.infn.it:4567/infn-cloud/webapp-rgw:latest
    env_file:
      - app/envs/prod.env
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
