version: '3'

services:
  frontend-dev:
    container_name: frontend-dev
    image: frontend-dev
    build:
      dockerfile: Dockerfile.dev
      context: frontend
    volumes:
      - ./frontend/:/app/
      - node_modules:/app/node_modules
    env_file:
      - frontend/envs/dev.env
  
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.prod
      args:
        - VERSION=1.2.3
    env_file:
      - frontend/envs/prod.env
  
  backend:
    container_name: backend
    image: backend
    build:
      context: backend
    volumes:
      - ./backend/src/:/app/
    environment:
      - WATCHFILES_FORCE_POLLING=true   # Enable uvicorn auto-reload
    env_file:
      - ./backend/envs/dev.env
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
      - 3000:3000

volumes:
  node_modules:
